# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'
source 'https://cdn.cocoapods.org/'

$grpcVersion = '1.0.0-alpha.20'
target 'test_sic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'KeychainSwift', '~> 19.0'
  pod 'Firebase/Messaging'
  pod 'gRPC-Swift', $grpcVersion
  pod 'gRPC-Swift-Plugins', $grpcVersion # this pod provides access to protoc-gen-grpc-swift and protoc-gen-swift plugins

end
