name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pod install Lib
      run: pod install --project-directory=./CleverAppWithLib

    - name: Pod install App
      run: pod install --project-directory=./test_sic

    - name: Build
      run: xcodebuild -workspace ./CleverAppWithLib/CleverAppWithLib.xcworkspace -scheme CleverAppWithLib

